Support communicating with postgres over VPC
cellarium-ai/cellarium-cloud pull request #156
Opened 2024-05-23 18:11 UTC by nmalfroy

This PR adds the ability to connect to cloud sql postgres using its private IP, which is over our VPC.  That's needed if we want to run the model and admin services behind the VPC (which we do)

This also documents how to connect to the services when they are not exposed to the internet.

My deployments are configured with this so you can check out how it works there.

2024-05-23 20:04 UTC, KevinCLydon requested changes
This is very cool.  I'm glad the change doesn't seem super complex.  I commented a couple small things, but otherwise this looks awesome! 👍

2024-05-24 14:50 UTC, nmalfroy commented on src/casp/services/db/__init__.py
> +            # pool_pre_ping=True,
Ah, because I forgot to remove it.

2024-05-24 16:06 UTC, fedorgrab approved these changes
All looks good to me!

2024-05-29 15:49 UTC, nmalfroy commented on src/casp/services/db/__init__.py
> +        driver="pg8000",
Yeah, I agree.  I guess they want to allow people rolling their own drivers?

2024-05-30 15:02 UTC, KevinCLydon approved these changes
Looks good!

2024-05-31 21:41 UTC, merged